version: '3.1'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-database
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: connect
    ports:
      - "3306:3306"
#    volumes:
#      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - connect-network

networks:
  connect-network:
