
spring:
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: ''

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/connect?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: qwer1234

token:
  access_expiration_time: 8640000000
  #  1day
  refresh_expiration_time: 8640000000
  secret: user_token